version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: php-apache/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./public_html:/var/www/html
      - ./logs/apache2:/var/log/apache2

  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
